name: Build and Release Windows App

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  release:
    types: [published]

jobs:
  build-windows:
    runs-on: windows-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install Git (if not available)
      run: |
        if (!(Get-Command git -ErrorAction SilentlyContinue)) {
          choco install git
        }

    - name: Install dependencies
      run: |
        npm install

    - name: Build renderer
      run: |
        npm run build-renderer

    - name: Install electron-builder
      run: |
        npm install --save-dev electron-builder

    - name: Build Windows executable
      run: |
        npm run dist
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: windows-app-build
        path: dist/*.exe
        if-no-files-found: warn

    - name: Create Release
      uses: softprops/action-gh-release@v2
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: dist/**
        name: Release ${{ github.ref_name }}
        draft: false
        prerelease: false
        generate_release_notes: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}